# Homebrew formula for Deckhand v0.1.1, generated by packaging/generate-manifests.sh.
#
#   brew install https://github.com/marcwoge/deckhand/releases/download/v0.1.1/deckhand.rb
#
# The binaries are the ones from the release, so the checksums below are the same
# ones listed in SHA256SUMS, which is signed with cosign.
class Deckhand < Formula
  desc "Watch GitHub repositories, pull new revisions, run your command"
  homepage "https://github.com/marcwoge/deckhand"
  version "0.1.1"
  license "Apache-2.0"

  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/marcwoge/deckhand/releases/download/v0.1.1/deckhand_v0.1.1_darwin_arm64"
      sha256 "c28de3bec5c1fa681a9edc4ae0bfdc919a0855352117ba7cd200e398f6717b65"
    end
    on_intel do
      url "https://github.com/marcwoge/deckhand/releases/download/v0.1.1/deckhand_v0.1.1_darwin_amd64"
      sha256 "744544b665d0ba815e74731885cd48c985d357896505c65af96b071d3a435dd4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/marcwoge/deckhand/releases/download/v0.1.1/deckhand_v0.1.1_linux_arm64"
      sha256 "009a66133d419a1acd0ce2b3674f71f0bce755d809e5e8430a644b32c21248b9"
    end
    on_intel do
      url "https://github.com/marcwoge/deckhand/releases/download/v0.1.1/deckhand_v0.1.1_linux_amd64"
      sha256 "2a8ada680163301ce3bf6c350ffe3b9b82332ed5be26d75712fc23ccf234a958"
    end
  end

  def install
    bin.install Dir["deckhand_*"].first => "deckhand"
  end

  def caveats
    <<~EOS
      Deckhand is installed but not configured. To get started:
        deckhand init --config ~/.config/deckhand/deckhand.yaml
        deckhand check
        deckhand service install

      Documentation: https://github.com/marcwoge/deckhand/tree/main/docs/en
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deckhand version")
  end
end
