#!/bin/sh
# Write the Homebrew formula and the Scoop manifest for a release, with the real
# checksums of the binaries in dist/.
#
# Both end up in dist/ before SHA256SUMS is computed, so the signature over that
# file covers them too: a tampered formula would be caught by the same check as a
# tampered binary.
#
#   ./packaging/generate-manifests.sh --tag v0.1.1
#
# There is no Homebrew tap and no Scoop bucket yet (see issue #8). Until there
# is, both files are published as release assets and can be installed directly
# from their URL - see docs/en/services.md.

set -eu

TAG=""
DIST="dist"
REPO="marcwoge/deckhand"

while [ $# -gt 0 ]; do
	case "$1" in
	--tag) TAG="${2:?--tag needs a version like v0.1.1}"; shift ;;
	--dist) DIST="${2:?--dist needs a directory}"; shift ;;
	--repo) REPO="${2:?--repo needs owner/name}"; shift ;;
	-h|--help) sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
	*) echo "unknown option $1" >&2; exit 2 ;;
	esac
	shift
done

[ -n "$TAG" ] || { echo "error: --tag is required" >&2; exit 2; }
VERSION="${TAG#v}"
BASE="https://github.com/$REPO/releases/download/$TAG"

hash_of() {
	# $1 asset name; empty output means the asset is not there.
	if [ ! -f "$DIST/$1" ]; then
		echo ""
		return
	fi
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$DIST/$1" | cut -d' ' -f1
	else
		shasum -a 256 "$DIST/$1" | cut -d' ' -f1
	fi
}

require() {
	# $1 name, $2 hash
	[ -n "$2" ] || { echo "error: $DIST/$1 is missing" >&2; exit 1; }
}

darwin_arm64="deckhand_${TAG}_darwin_arm64"
darwin_amd64="deckhand_${TAG}_darwin_amd64"
linux_arm64="deckhand_${TAG}_linux_arm64"
linux_amd64="deckhand_${TAG}_linux_amd64"
win_amd64="deckhand_${TAG}_windows_amd64.exe"
win_arm64="deckhand_${TAG}_windows_arm64.exe"

h_darwin_arm64="$(hash_of "$darwin_arm64")"; require "$darwin_arm64" "$h_darwin_arm64"
h_darwin_amd64="$(hash_of "$darwin_amd64")"; require "$darwin_amd64" "$h_darwin_amd64"
h_linux_arm64="$(hash_of "$linux_arm64")";   require "$linux_arm64" "$h_linux_arm64"
h_linux_amd64="$(hash_of "$linux_amd64")";   require "$linux_amd64" "$h_linux_amd64"
h_win_amd64="$(hash_of "$win_amd64")";       require "$win_amd64" "$h_win_amd64"
h_win_arm64="$(hash_of "$win_arm64")";       require "$win_arm64" "$h_win_arm64"

cat > "$DIST/deckhand.rb" <<FORMULA
# Homebrew formula for Deckhand $TAG, generated by packaging/generate-manifests.sh.
#
#   brew install $BASE/deckhand.rb
#
# The binaries are the ones from the release, so the checksums below are the same
# ones listed in SHA256SUMS, which is signed with cosign.
class Deckhand < Formula
  desc "Watch GitHub repositories, pull new revisions, run your command"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "Apache-2.0"

  depends_on "git"

  on_macos do
    on_arm do
      url "$BASE/$darwin_arm64"
      sha256 "$h_darwin_arm64"
    end
    on_intel do
      url "$BASE/$darwin_amd64"
      sha256 "$h_darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/$linux_arm64"
      sha256 "$h_linux_arm64"
    end
    on_intel do
      url "$BASE/$linux_amd64"
      sha256 "$h_linux_amd64"
    end
  end

  def install
    bin.install Dir["deckhand_*"].first => "deckhand"
  end

  def caveats
    <<~EOS
      Deckhand is installed but not configured. To get started:
        deckhand init --config ~/.config/deckhand/deckhand.yaml
        deckhand check
        deckhand service install

      Documentation: https://github.com/$REPO/tree/main/docs/en
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deckhand version")
  end
end
FORMULA

cat > "$DIST/deckhand.json" <<MANIFEST
{
    "version": "$VERSION",
    "description": "Watch GitHub repositories, pull new revisions, run your command",
    "homepage": "https://github.com/$REPO",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "$BASE/$win_amd64#/deckhand.exe",
            "hash": "$h_win_amd64"
        },
        "arm64": {
            "url": "$BASE/$win_arm64#/deckhand.exe",
            "hash": "$h_win_arm64"
        }
    },
    "bin": "deckhand.exe",
    "checkver": {
        "github": "https://github.com/$REPO"
    },
    "notes": [
        "Deckhand is installed but not configured. To get started:",
        "  deckhand init --config %USERPROFILE%\\\\deckhand\\\\deckhand.yaml",
        "  deckhand check",
        "  deckhand service install",
        "Documentation: https://github.com/$REPO/tree/main/docs/en"
    ]
}
MANIFEST

echo "wrote $DIST/deckhand.rb and $DIST/deckhand.json for $TAG"
