#!/bin/sh
# Write the Homebrew formula and the Scoop manifest for a release, with the real
# checksums of the binaries in dist/.
#
# Both end up in dist/ before SHA256SUMS is computed, so the signature over that
# file covers them too: a tampered formula would be caught by the same check as a
# tampered binary.
#
#   ./packaging/generate-manifests.sh --tag v0.1.1
#
# With --from-release it takes the checksums from the release's own SHA256SUMS
# instead of hashing local files, and verifies that file's cosign signature
# first when cosign is installed. That is the mode the tap and the bucket use to
# update themselves: they never download a binary, and they trust the same signed
# file a careful human would check.
#
#   ./packaging/generate-manifests.sh --tag v0.1.1 --from-release --dist out

set -eu

TAG=""
DIST="dist"
REPO="marcwoge/deckhand"
FROM_RELEASE=0

while [ $# -gt 0 ]; do
	case "$1" in
	--tag) TAG="${2:?--tag needs a version like v0.1.1}"; shift ;;
	--dist) DIST="${2:?--dist needs a directory}"; shift ;;
	--repo) REPO="${2:?--repo needs owner/name}"; shift ;;
	--from-release) FROM_RELEASE=1 ;;
	-h|--help) sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
	*) echo "unknown option $1" >&2; exit 2 ;;
	esac
	shift
done

if [ -z "$TAG" ] && [ "$FROM_RELEASE" -eq 1 ]; then
	TAG="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" |
		sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)"
	[ -n "$TAG" ] || { echo "error: cannot determine the latest release" >&2; exit 1; }
	echo "latest release: $TAG"
fi
[ -n "$TAG" ] || { echo "error: --tag is required" >&2; exit 2; }
VERSION="${TAG#v}"
BASE="https://github.com/$REPO/releases/download/$TAG"

mkdir -p "$DIST"

SUMS=""
if [ "$FROM_RELEASE" -eq 1 ]; then
	SUMS="$DIST/SHA256SUMS.release"
	curl -fsSL -o "$SUMS" "$BASE/SHA256SUMS" ||
		{ echo "error: $TAG has no SHA256SUMS" >&2; exit 1; }

	# The checksums are only worth anything if the file carrying them is the one
	# the release workflow signed. Without cosign the hashes are still correct
	# for whatever is published, which is enough to build a manifest, but say so.
	if command -v cosign >/dev/null 2>&1; then
		curl -fsSL -o "$SUMS.bundle" "$BASE/SHA256SUMS.bundle" ||
			{ echo "error: $TAG has no signature" >&2; exit 1; }
		cosign verify-blob "$SUMS" \
			--bundle "$SUMS.bundle" \
			--certificate-identity-regexp \
			"https://github.com/$REPO/.github/workflows/release.yml@.*" \
			--certificate-oidc-issuer https://token.actions.githubusercontent.com ||
			{ echo "error: the checksum file is not signed by $REPO's release workflow" >&2
				exit 1; }
		echo "signature verified"
	else
		echo "warning: cosign is not installed, so the checksum file is used unverified" >&2
	fi
fi

hash_of() {
	# $1 asset name. Empty output means it is not there.
	if [ -n "$SUMS" ]; then
		# The release's own checksums: "<hash>  <name>".
		awk -v want="$1" '$2 == want || $2 == "*" want { print $1; exit }' "$SUMS"
		return
	fi
	if [ ! -f "$DIST/$1" ]; then
		echo ""
		return
	fi
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$DIST/$1" | cut -d' ' -f1
	else
		shasum -a 256 "$DIST/$1" | cut -d' ' -f1
	fi
}

require() {
	# $1 name, $2 hash
	if [ -z "$2" ]; then
		if [ -n "$SUMS" ]; then
			echo "error: $1 is not listed in the release's SHA256SUMS" >&2
		else
			echo "error: $DIST/$1 is missing" >&2
		fi
		exit 1
	fi
}

darwin_arm64="deckhand_${TAG}_darwin_arm64"
darwin_amd64="deckhand_${TAG}_darwin_amd64"
linux_arm64="deckhand_${TAG}_linux_arm64"
linux_amd64="deckhand_${TAG}_linux_amd64"
win_amd64="deckhand_${TAG}_windows_amd64.exe"
win_arm64="deckhand_${TAG}_windows_arm64.exe"

h_darwin_arm64="$(hash_of "$darwin_arm64")"; require "$darwin_arm64" "$h_darwin_arm64"
h_darwin_amd64="$(hash_of "$darwin_amd64")"; require "$darwin_amd64" "$h_darwin_amd64"
h_linux_arm64="$(hash_of "$linux_arm64")";   require "$linux_arm64" "$h_linux_arm64"
h_linux_amd64="$(hash_of "$linux_amd64")";   require "$linux_amd64" "$h_linux_amd64"
h_win_amd64="$(hash_of "$win_amd64")";       require "$win_amd64" "$h_win_amd64"
h_win_arm64="$(hash_of "$win_arm64")";       require "$win_arm64" "$h_win_arm64"

cat > "$DIST/deckhand.rb" <<FORMULA
# Homebrew formula for Deckhand $TAG, generated by packaging/generate-manifests.sh.
#
#   brew install $BASE/deckhand.rb
#
# The binaries are the ones from the release, so the checksums below are the same
# ones listed in SHA256SUMS, which is signed with cosign.
class Deckhand < Formula
  desc "Watch GitHub repositories, pull new revisions, run your command"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "Apache-2.0"

  depends_on "git"

  on_macos do
    on_arm do
      url "$BASE/$darwin_arm64"
      sha256 "$h_darwin_arm64"
    end
    on_intel do
      url "$BASE/$darwin_amd64"
      sha256 "$h_darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/$linux_arm64"
      sha256 "$h_linux_arm64"
    end
    on_intel do
      url "$BASE/$linux_amd64"
      sha256 "$h_linux_amd64"
    end
  end

  def install
    bin.install Dir["deckhand_*"].first => "deckhand"
  end

  def caveats
    <<~EOS
      Deckhand is installed but not configured. To get started:
        deckhand init --config ~/.config/deckhand/deckhand.yaml
        deckhand check
        deckhand service install

      Documentation: https://github.com/$REPO/tree/main/docs/en
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deckhand version")
  end
end
FORMULA

cat > "$DIST/deckhand.json" <<MANIFEST
{
    "version": "$VERSION",
    "description": "Watch GitHub repositories, pull new revisions, run your command",
    "homepage": "https://github.com/$REPO",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "$BASE/$win_amd64#/deckhand.exe",
            "hash": "$h_win_amd64"
        },
        "arm64": {
            "url": "$BASE/$win_arm64#/deckhand.exe",
            "hash": "$h_win_arm64"
        }
    },
    "bin": "deckhand.exe",
    "checkver": {
        "github": "https://github.com/$REPO"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/$REPO/releases/download/v\$version/deckhand_v\$version_windows_amd64.exe#/deckhand.exe"
            },
            "arm64": {
                "url": "https://github.com/$REPO/releases/download/v\$version/deckhand_v\$version_windows_arm64.exe#/deckhand.exe"
            }
        },
        "hash": {
            "url": "https://github.com/$REPO/releases/download/v\$version/SHA256SUMS"
        }
    },
    "notes": [
        "Deckhand is installed but not configured. To get started:",
        "  deckhand init --config %USERPROFILE%\\\\deckhand\\\\deckhand.yaml",
        "  deckhand check",
        "  deckhand service install",
        "Documentation: https://github.com/$REPO/tree/main/docs/en"
    ]
}
MANIFEST

echo "wrote $DIST/deckhand.rb and $DIST/deckhand.json for $TAG"
